# Generated by Django 3.0.2 on 2020-02-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200107_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('eamil', models.EmailField(max_length=254)),
                ('price', models.IntegerField(default='0')),
                ('desc', models.CharField(max_length=300)),
            ],
        ),
    ]
