# Generated by Django 3.0.2 on 2020-02-04 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='price',
            new_name='mobile',
        ),
    ]
