# Generated by Django 3.0.2 on 2020-02-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200204_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='eamil',
            new_name='email',
        ),
    ]
