# Generated by Django 3.0.3 on 2020-03-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Amount',
            field=models.IntegerField(default='0'),
        ),
    ]
