# Generated by Django 3.0.3 on 2020-03-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='Amount',
            field=models.IntegerField(default='0'),
        ),
    ]
